"""
reporter.py
The Reporter Agent.
LangGraph node that generates an 'Executive Action Report' using Cerebras gpt-oss-120b.
Persona: Executive Compliance Officer.
"""

import os
import json
import requests
import pandas as pd
from typing import Optional
from typing_extensions import TypedDict
from langgraph.graph import StateGraph


# ── State ────────────────────────────────────────────────────────────────────

class ReporterState(TypedDict):
    summary_json: str          # Raw JSON string of summary stats
    violations_preview: str    # Top 5 violations as markdown table
    report: Optional[str]      # Generated markdown report
    error: Optional[str]


# ── Paths ────────────────────────────────────────────────────────────────────

SUMMARY_JSON = "outputs/summary_stats.json"
VIOLATIONS_CSV = "outputs/violations.csv"
REPORT_MD = "outputs/executive_report.md"


# ── Cerebras Call ────────────────────────────────────────────────────────────

def _call_cerebras(prompt: str, temperature: float = 0.3) -> str:
    """Call Cerebras gpt-oss-120b API."""
    api_key = os.getenv("CEREBRAS_API_KEY")
    if not api_key:
        raise RuntimeError("CEREBRAS_API_KEY not set")
    
    url = "https://api.cerebras.ai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    data = {
        "model": "gpt-oss-120b",
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an Executive Compliance Officer. "
                    "You write urgent, professional Executive Action Reports for senior leadership. "
                    "Your tone is direct, metric-driven, and action-oriented. "
                    "You use emojis strategically (🚨 💰 ✅ ⚠️) for emphasis. "
                    "You never use fluff or filler. Every sentence drives a decision. "
                    "You output ONLY valid Markdown. No code fences wrapping the markdown."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        "max_tokens": 1500,
        "temperature": temperature,
    }
    
    resp = requests.post(url, headers=headers, json=data)
    if resp.status_code != 200:
        raise RuntimeError(f"Cerebras API error: {resp.status_code} - {resp.text}")
    
    return resp.json()["choices"][0]["message"]["content"]


# ── LangGraph Node ───────────────────────────────────────────────────────────

def generate_report_node(state: ReporterState) -> ReporterState:
    """LangGraph node: Generate the War Room Brief from stats + violations."""
    try:
        summary = json.loads(state["summary_json"])
        
        prompt = f"""Write an 'Executive Action Report' — a Daily Compliance Brief for senior leadership.

## DATA PROVIDED

### Summary Stats
{json.dumps(summary, indent=2)}

### Top Violations (Preview)
{state['violations_preview']}

## REPORT STRUCTURE (follow exactly)

1. **Header**: "# ⚙️ Executive Action Report" with today's date and "SOP Compliance Brief"

2. **Executive Summary**: One punchy paragraph. Total records scanned, violation rate, trapped capital amount. Set the tone.

3. **Section: 🚨 CRITICAL ACTIONS — Non-Compliant Assets**
   - How many items flagged for disposition (Liquidation status)
   - Total Trapped Capital (dollar amount from stats)
   - Average age metric for flagged items
   - Recommendation: "APPROVE DISPOSITION within 48 hours or capital remains frozen."

4. **Section: ⚠️ MARGIN WATCH — Low-Performance Items**
   - How many items under Review
   - Total margin at risk
   - Average profit per item
   - Recommendation: reprice or bundle

5. **Section: ✅ WINS — High-Value Assets Preserved**
   - How many VIP_Keep items preserved from false disposition
   - Total value preserved
   - Average profit of saved items
   - Frame this as "value protected by the SOP Compiler"

6. **Section: 📋 Top Violations Preview** — Show the violations table from the data above.

7. **Footer**: "Report generated by Agentic SOP Compiler v1.0 | Automated — No human bias."

Keep it under 400 words. Every line must drive a decision."""

        report = _call_cerebras(prompt)
        
        # Strip any markdown code fences the LLM might wrap around the output
        report = report.strip()
        if report.startswith("```markdown"):
            report = report[len("```markdown"):].strip()
        if report.startswith("```"):
            report = report[3:].strip()
        if report.endswith("```"):
            report = report[:-3].strip()
        
        return {**state, "report": report, "error": None}
    
    except Exception as e:
        return {**state, "report": None, "error": str(e)}


# ── Graph Builder ────────────────────────────────────────────────────────────

def build_reporter_graph():
    """Build and compile the reporter LangGraph."""
    graph = StateGraph(ReporterState)
    graph.add_node("generate_report", generate_report_node)
    graph.set_entry_point("generate_report")
    graph.set_finish_point("generate_report")
    return graph.compile()


# ── Public API ───────────────────────────────────────────────────────────────

def generate_war_room_brief(
    summary_path: str = SUMMARY_JSON,
    violations_path: str = VIOLATIONS_CSV,
    save_to_file: bool = True,
) -> str | None:
    """
    High-level function: Load stats + violations, generate report.
    
    Args:
        summary_path: Path to summary_stats.json
        violations_path: Path to violations.csv
        save_to_file: If True, save report to outputs/executive_report.md
        
    Returns:
        Markdown report string, or None on error
    """
    # Load summary
    with open(summary_path, "r") as f:
        summary_json = f.read()
    
    # Load top 5 violations as markdown table
    df = pd.read_csv(violations_path)
    top5 = df.head(5)
    violations_preview = top5.to_markdown(index=False)
    
    # Run graph
    graph = build_reporter_graph()
    initial_state: ReporterState = {
        "summary_json": summary_json,
        "violations_preview": violations_preview,
        "report": None,
        "error": None,
    }
    
    final_state = graph.invoke(initial_state)
    
    if final_state["error"]:
        print(f"❌ Reporter error: {final_state['error']}")
        return None
    
    report = final_state["report"]
    
    if save_to_file and report:
        with open(REPORT_MD, "w") as f:
            f.write(report)
        print(f"✅ Executive Action Report saved to {REPORT_MD}")
    
    return report


if __name__ == "__main__":
    report = generate_war_room_brief()
    if report:
        print("\n" + "=" * 60)
        print(report)
        print("=" * 60)
    else:
        print("❌ Failed to generate executive report")
